version: '2'
services:
  ai:
    image: ai:latest
    command: ["run"]
    network_mode: "host"
    env_file:
      - .env
  tts:
    image: ghcr.io/coqui-ai/tts-cpu
    entrypoint: ["python3", "TTS/server/server.py", "--model_name", "tts_models/en/vctk/vits"]
    ports:
      - 5002:5002
    network_mode: "host"